// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://xnpvvcisithftraeykia.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_QzhhWH8rW1Zae6HUi9IIkA_tQcJlqie";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
