// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://imlbvvxyxlknevvlbbpr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImltbGJ2dnh5eGxrbmV2dmxiYnByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk5Mjg3NjYsImV4cCI6MjA4NTUwNDc2Nn0.kJ9LExD3-x0h5IwJ1TFwZtEyvwOnp5s9CpXV9CKajUA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
